version: '2'
services:
    sensorius-app:
        container_name: sensorius
        build:
            dockerfile: Dockerfile
        image: sensorius:latest
        environment:
        	- spring.kafka.consumer.enable-auto-commit=true
        	- com.gustinmi.sensorius.topic-name=sensor-data
			- com.gustinmi.sensorius.group-name=tGroup1
			- com.gustinmi.sensorius.health-port=8097
        ports:
            - 8097:8097